[2025-03-26T00:18:00.163+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: titanic_survival_classifier.model_training_task manual__2025-03-26T00:17:50.145574+00:00 [queued]>
[2025-03-26T00:18:00.182+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: titanic_survival_classifier.model_training_task manual__2025-03-26T00:17:50.145574+00:00 [queued]>
[2025-03-26T00:18:00.183+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-26T00:18:00.212+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): model_training_task> on 2025-03-26 00:17:50.145574+00:00
[2025-03-26T00:18:00.226+0000] {standard_task_runner.py:60} INFO - Started process 443 to run task
[2025-03-26T00:18:00.230+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'titanic_survival_classifier', 'model_training_task', 'manual__2025-03-26T00:17:50.145574+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpda__63j_']
[2025-03-26T00:18:00.232+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask model_training_task
[2025-03-26T00:18:00.260+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-26T00:18:00.341+0000] {task_command.py:423} INFO - Running <TaskInstance: titanic_survival_classifier.model_training_task manual__2025-03-26T00:17:50.145574+00:00 [running]> on host 0f3b2e2ddf0a
[2025-03-26T00:18:00.487+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='titanic_survival_classifier' AIRFLOW_CTX_TASK_ID='model_training_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T00:17:50.145574+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T00:17:50.145574+00:00'
[2025-03-26T00:18:00.505+0000] {logging_mixin.py:188} INFO - ---Training Model---
[2025-03-26T00:18:01.027+0000] {logging_mixin.py:188} INFO - Validation Accuracy: 0.8156
[2025-03-26T00:18:01.063+0000] {logging_mixin.py:188} INFO - Saved model to /opt/***/data/train/titanic_model.pkl
[2025-03-26T00:18:01.084+0000] {python.py:201} INFO - Done. Returned value was: {'validation_accuracy': 0.8156424581005587, 'model_path': '/opt/***/data/train/titanic_model.pkl'}
[2025-03-26T00:18:01.171+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=titanic_survival_classifier, task_id=model_training_task, execution_date=20250326T001750, start_date=20250326T001800, end_date=20250326T001801
[2025-03-26T00:18:01.275+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-26T00:18:01.339+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
